name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the source
      uses: actions/checkout@v4
    
    - name: Docker Login 
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag node-app:1
    
    - name: Tag the Docker image
      run: docker tag node-app:1 ${{secrets.DOCKER_USERNAME}}/node-app:1
    
    - name: Push Docker image
      run: docker push ${{secrets.DOCKER_USERNAME}}/node-app:1

  deploy:
    needs: build
    runs-on: [self-hosted,ubuntu-latest]
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{secrets.DOCKER_USERNAME}}/node-app:1
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container ${{secrets.DOCKER_USERNAME}}/node-app:1


